mod gitall x86_64-pc-linux-gnu-peng

diff --git a/_bashrc b/_bashrc
--- a/_bashrc
+++ b/_bashrc
@@ -4,7 +4,7 @@
 # Summary: bash config for at least Unix, Linux, Cygwin and z/OS
 #
 #  Created: Tue 19-May-1998 (Bob Heckel)
-# Modified: Sat 13-Feb-2021 (Bob Heckel)
+# Modified: Sat 20-Feb-2021 (Bob Heckel)
 #^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^
 
 #----------------
@@ -472,24 +472,23 @@ case "$OSTYPE" in
     # Functions Cygwin  #{{{2
     #-------------------
 
-      if [ ${OSTYPE:0:6} = 'cygwin' ]; then
-        function catput() {
+    if [ ${OSTYPE:0:6} = 'cygwin' ]; then
+      function catput() {
+        echo 'putclip...'
+        if [ -e /usr/bin/putclip ]; then
           echo 'putclip...'
-          if [ -e /usr/bin/putclip ]; then
-            echo 'putclip...'
-            cat "$1" | putclip
-          else
-            echo putclip not installed
-          fi
-        }
-      fi
+          cat "$1" | putclip
+        else
+          echo putclip not installed
+        fi
+      }
+    fi
 
     # end Functions Cygwin
 
     #-------------------
     # Alias Cygwin  #{{{2
     #-------------------
-    # alias catput=$HOME/code/misc/catput.sh
     alias d1='vim /cygdrive/c/temp/1 /cygdrive/c/temp/2'
     alias d2='vim /cygdrive/c/temp/2'
     alias d12="(cd /cygdrive/c/temp; vi -Rc 'map q :qa<CR>' -Rd 1 2)"
@@ -625,8 +624,6 @@ case "$OSTYPE" in
       # Alias Linux  #{{{2 
       #----------------
 
-      # Overridden by hostname
-      # alias catput=$HOME/code/misc/catput.sh
       # Quick diff
       alias d1="vim $HOME/tmp/1 $HOME/tmp/2"
       alias d2="vim $HOME/tmp/2"
@@ -740,27 +737,49 @@ case "$OSTYPE" in
           fi
         fi
 
-        alias vi='~/bin/vim -u ~/code/misc/_vimrc'
-###        export VIMRUNTIME=/home/chronos/user/.vim
+        # export VIMRUNTIME=/home/chronos/user/.vim
       fi
 
       # if [ $HOSTNAME = 'penguin' ] && [ -n "$TMUX" ]; then
       if [ $HOSTNAME = 'penguin' ];then
-        function catput() {
-          buf=$(head -n500 ${1})
-          # Mask for printf
-          buf2=$(echo $buf | sed 's/%/%%/')
 
-          #TODO how to tell if TMUX is running IN THIS TERMINAL
+        # read_input buf <t.txt
+        read_input() {
+          : "${1:?Must provide a variable to read into}"
+
+          if [[ "$1" == '_line' || "$1" == '_contents' ]]; then
+            echo "Cannot store contents to $1, use a different name." >&2
+            return 1
+          fi
+
+          local _line _contents=()
+           while IFS='' read -r _line; do
+             _contents+=("$_line"$'\n')
+           done
+           # Include $_line once more to capture any content after the last newline
+           printf -v "$1" '%s' "${_contents[@]}" "$_line"
+        }
+
+        #TODO fails on large files
+        function catput() {
+          # buf=$(head -n5000 ${1})
+          buf=$(cat ${1})
+          # Mask for printf
+          # buf2=$(echo $buf | sed 's/%/%%/')
+          #TODO use bash regex to fix the '%'
+          buf2="${buf}"
+
+          #TODO how to tell if TMUX is running IN THIS TERMINAL not just anywhere
           if [ -n ${TMUX} ];then
             echo 'tmux printf...'
-            printf "\033]52;c;$(printf $buf2 "" | base64)\a" >/dev/pts/0
+            printf "\033]52;c;$(printf "${buf2}" | base64)\a" >/dev/pts/0
           else
             echo 'printf...'
-            printf "\033]52;c;$(printf $buf2 "" | base64)\a"
+            printf "\033]52;c;$(printf "${buf2}" | base64)\a"
           fi
         }
-      fi
+
+      fi  # penguin
 
       # Use: bigshell FONTSIZE (where fontsize defaults to 16)
       function bigshell() {
