mod

diff --git a/_bashrc b/_bashrc
--- a/_bashrc
+++ b/_bashrc
@@ -4,7 +4,7 @@
 # Summary: bash shell config for at least Cygwin 1.3/1.5/1.7, Unix and z/OS
 #
 #  Created: Tue 19 May 1998 08:21:18 (Bob Heckel)
-# Modified: Fri 03 Aug 2012 17:27:23 (Bob Heckel)
+# Modified: Sun 16 Sep 2012 12:37:06 (Bob Heckel)
 #^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^~^
 
 #----------------
@@ -44,6 +44,14 @@ export PARINIT='rTbgqR B=.?_A_a Q=_s>| w65'  # par formatter
 export TMP=$HOME/tmp
 # Default "unknown host" indicator for my .vimrc statusline
 export VIMSTATUSL='?@?'
+
+GREP_OPTIONS=
+if grep --help | grep -- --exclude-dir &>/dev/null; then
+  for PATTERN in .cvs .git .hg .svn; do
+    GREP_OPTIONS="$GREP_OPTIONS --exclude-dir=$PATTERN"
+  done
+fi
+export GREP_OPTIONS
 
 # Used by at least PS1, also good for use in shell scripts.  But bad for when printing env
 # Ctrl-v escape to insert the ^[
@@ -87,7 +95,8 @@ alias cdvb="cd $HOME/code/vb"
 alias cls=clear  # like Windows
 alias f='fg'  # jobs -s  to list what's suspended
 alias g=$HOME/code/misccode/gone.sh
-alias gitlog='git log --pretty=format:"%h %ad | %s%d [%an]" --graph --date=short'
+alias gi='git ls-files -o -i --exclude-standard'  # git ignores
+alias gl='git log --pretty=format:"%h %ad | %s%d [%an]" --graph --date=short'
 alias gs='git status'
 alias h='history|tail -20'  # history 20 is better if it exists
 alias iv=vi
@@ -872,15 +881,15 @@ case "$OSTYPE" in
     # Present Working Windows Directory
     alias pwwd='cygpath -w "`pwd`"'
     ###alias runllg="w3m -no-cookie -dump_source 'http://rtpsawn321/links/runllg.asp?action=Run+LLG'|grep '^LLG'"
-    alias runllg="w3m -no-cookie -dump_source 'http://rtpsawn321/links/runllg.asp?action=Run+LLG'|grep '^LLG' ; grep ERRMSG /cygdrive/x/SQL_Loader/Logs/LGI.log || echo fail"
+###    alias runllg="w3m -no-cookie -dump_source 'http://rtpsawn321/links/runllg.asp?action=Run+LLG'|grep '^LLG' ; grep ERRMSG /cygdrive/x/SQL_Loader/Logs/LGI.log || echo fail"
     alias sas="c:/Program\ Files/SAS\ Institute/SAS/V8/sas.exe"
     ###alias sas8="c:/Program\ Files/SAS\ Institute/SAS/V8/sas.exe"
     ###alias sas9="c:/Program\ Files/SAS/SAS\ 9.1/sas.exe"
-    alias sasdate=$HOME/code/misccode/sasdate
+###    alias sasdate=$HOME/code/misccode/sasdate
     alias sasrun=$HOME/code/misccode/sasrun
     alias sensible-browser="/cygdrive/c/Program\ Files/mozilla\ firefox/firefox.exe"
-    alias usb="$HOME/bin/USB_Disk_Eject /removename '*LEXAR'"
-    alias usbe="$HOME/bin/USB_Disk_Eject /removeletter E"
+###    alias usb="$HOME/bin/USB_Disk_Eject /removename '*LEXAR'"
+###    alias usbe="$HOME/bin/USB_Disk_Eject /removeletter E"
     alias uvi=$HOME/code/perl/uvi  # don't change timestamp
     alias v="vim -u $HOME/code/misccode/.vimrc.more"  # alternative to 'm'
     alias vi=vim
@@ -1070,7 +1079,7 @@ case "$OSTYPE" in
 
       if [ $HOSTNAME = 'yoniso' ]; then
         # TODO if not running start dropbox and nm-applet
-        alias nexus='sudo mount -t vfat /dev/sdb /media/Nexus -o uid=1000,gid=1000,utf8,dmask=027,fmask=137; echo "sudo umount /media/Nexus"'
+        alias nexus='sudo mount -t vfat /dev/sdb /media/Nexus -o uid=1000,gid=1000,utf8,dmask=027,fmask=137; mount|grep "^/dev/sd"; echo "sudo umount /media/Nexus"'
       fi
 
       export PROMPT_COMMAND='history -a; echo -ne "\033]0;${HOSTNAME:0:4}:${PWD}\007";'
@@ -1090,9 +1099,7 @@ case "$OSTYPE" in
         ###if [ -z "$(pgrep conky)" ]; then
           ###conky -x 5 -y 0 &
         ###fi
-        alias sb='sudo mount -t vfat /dev/sdb1 /media/Lexar -o uid=1000,gid=1000,utf8,dmask=027,fmask=137 && mount|grep "^/dev" && sleep 5 && SyncBackSE.exe && sleep 5 && sudo umount /media/Lexar && mount|grep "^/dev"'
-        # same
-        alias syncback='sudo mount -t vfat /dev/sdb1 /media/Lexar -o uid=1000,gid=1000,utf8,dmask=027,fmask=137 && sleep 5 && SyncBackSE.exe && sleep 5 && sudo umount /media/Lexar'
+        alias sb='sudo mount -t vfat /dev/sdb1 /media/Lexar -o uid=1000,gid=1000,utf8,dmask=027,fmask=137 && mount|grep "^/dev/sd" && sleep 5 && echo && SyncBackSE.exe && sleep 5 && echo && sudo umount /media/Lexar && mount|grep "^/dev/sd"'
       fi
 
       alias d12="(cd ~/tmp; vi -d 1 2)"
@@ -1207,15 +1214,6 @@ esac #}}}
 #}}}1
 
 if [ -e $HOME/code/misccode/_project.bashrc ]; then
-    # Project-specific or security related additions
+  # Project-specific or security related additions
   source $HOME/code/misccode/_project.bashrc
 fi
-
-
-GREP_OPTIONS=
-if grep --help | grep -- --exclude-dir &>/dev/null; then
-    for PATTERN in .cvs .git .hg .svn; do
-        GREP_OPTIONS="$GREP_OPTIONS --exclude-dir=$PATTERN"
-    done
-fi
-export GREP_OPTIONS
